build-abi:
	cargo build
run-dummy:
	RUST_LOGO=info cargo run --example dummy_server --quiet
run-server:
	RUST_LOGO=info cargo run --example server --quiet
run-client:
	RUST_LOGO=info cargo run --example client --quiet